#!/bin/bash
echo "-------------------------------------------------------"
echo "Preparing PHP code"
echo "-------------------------------------------------------"
cd $OPENSHIFT_REPO_DIR
composer.phar install --no-dev

echo "-------------------------------------------------------"
echo "Installing product"
echo "-------------------------------------------------------"
mv ./.openshift/config.yml ./PHPCI/config.yml
