b8:
	database:
			servers:
				read: "%OPENSHIFT_MYSQL_DB_HOST%"
				write: "%OPENSHIFT_MYSQL_DB_HOST%"
			name: "%OPENSHIFT_APP_NAME%"
			username: "%OPENSHIFT_MYSQL_DB_USERNAME%"
			password: "%OPENSHIFT_MYSQL_DB_PASSWORD%"
phpci:
	url: "%OPENSHIFT_APP_DNS%"
